src_len: 512
tgt_len: 64
metrics: ['rouge']
metrics_for_best_model: ['rouge-l']
is_chinese_task: True
rouge_type: 'rouge'

epochs: 10
label_smoothing: 0.1
stopping_steps: 10
learning_rate: 1e-5
train_batch_size: 16
eval_batch_size: 16
prefix_prompt: 'Summarize: '
